//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zamov.srSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.mobisoftline.com/", ConfigurationName="srSms.NotificatorServiceDelegate")]
    public interface NotificatorServiceDelegate {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseSynchData))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Zamov.srSms.sendMessagesResponse sendMessages(Zamov.srSms.sendMessagesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseSynchData))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Zamov.srSms.requestNotificationStatusResponse requestNotificationStatus(Zamov.srSms.requestNotificationStatusRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseSynchData))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Zamov.srSms.requestMessageStatusResponse requestMessageStatus(Zamov.srSms.requestMessageStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class notification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string alfaNameField;
        
        private contact[] contactsField;
        
        private int priorityField;
        
        private string templateField;
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alfaName {
            get {
                return this.alfaNameField;
            }
            set {
                this.alfaNameField = value;
                this.RaisePropertyChanged("alfaName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contacts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public contact[] contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
                this.RaisePropertyChanged("contacts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
                this.RaisePropertyChanged("template");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class contact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] paramsField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("params", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(messageRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(notificationRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long requestIDField;
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class messageRequest : request {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class notificationRequest : request {
        
        private int statusTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
                this.RaisePropertyChanged("statusType");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(status))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(responseMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class responseSynchData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorDescriptionField;
        
        private int notificationResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int notificationResponse {
            get {
                return this.notificationResponseField;
            }
            set {
                this.notificationResponseField = value;
                this.RaisePropertyChanged("notificationResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class status : responseSynchData {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private long idField;
        
        private string phoneField;
        
        private int status1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int status1 {
            get {
                return this.status1Field;
            }
            set {
                this.status1Field = value;
                this.RaisePropertyChanged("status1");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mobisoftline.com/")]
    public partial class responseMessage : responseSynchData {
        
        private int acceptedField;
        
        private int deliveredField;
        
        private int expiredField;
        
        private long notificationIDField;
        
        private status[] statusesField;
        
        private int totalField;
        
        private int undeliverableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int accepted {
            get {
                return this.acceptedField;
            }
            set {
                this.acceptedField = value;
                this.RaisePropertyChanged("accepted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int delivered {
            get {
                return this.deliveredField;
            }
            set {
                this.deliveredField = value;
                this.RaisePropertyChanged("delivered");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int expired {
            get {
                return this.expiredField;
            }
            set {
                this.expiredField = value;
                this.RaisePropertyChanged("expired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long notificationID {
            get {
                return this.notificationIDField;
            }
            set {
                this.notificationIDField = value;
                this.RaisePropertyChanged("notificationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statuses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public status[] statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
                this.RaisePropertyChanged("statuses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int undeliverable {
            get {
                return this.undeliverableField;
            }
            set {
                this.undeliverableField = value;
                this.RaisePropertyChanged("undeliverable");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessages", WrapperNamespace="http://ws.mobisoftline.com/", IsWrapped=true)]
    public partial class sendMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mobisoftline.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zamov.srSms.notification arg0;
        
        public sendMessagesRequest() {
        }
        
        public sendMessagesRequest(Zamov.srSms.notification arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessagesResponse", WrapperNamespace="http://ws.mobisoftline.com/", IsWrapped=true)]
    public partial class sendMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mobisoftline.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zamov.srSms.responseMessage @return;
        
        public sendMessagesResponse() {
        }
        
        public sendMessagesResponse(Zamov.srSms.responseMessage @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestNotificationStatus", WrapperNamespace="http://ws.mobisoftline.com/", IsWrapped=true)]
    public partial class requestNotificationStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mobisoftline.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zamov.srSms.notificationRequest arg0;
        
        public requestNotificationStatusRequest() {
        }
        
        public requestNotificationStatusRequest(Zamov.srSms.notificationRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestNotificationStatusResponse", WrapperNamespace="http://ws.mobisoftline.com/", IsWrapped=true)]
    public partial class requestNotificationStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mobisoftline.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zamov.srSms.responseMessage @return;
        
        public requestNotificationStatusResponse() {
        }
        
        public requestNotificationStatusResponse(Zamov.srSms.responseMessage @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestMessageStatus", WrapperNamespace="http://ws.mobisoftline.com/", IsWrapped=true)]
    public partial class requestMessageStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mobisoftline.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zamov.srSms.messageRequest arg0;
        
        public requestMessageStatusRequest() {
        }
        
        public requestMessageStatusRequest(Zamov.srSms.messageRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestMessageStatusResponse", WrapperNamespace="http://ws.mobisoftline.com/", IsWrapped=true)]
    public partial class requestMessageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mobisoftline.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zamov.srSms.status @return;
        
        public requestMessageStatusResponse() {
        }
        
        public requestMessageStatusResponse(Zamov.srSms.status @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotificatorServiceDelegateChannel : Zamov.srSms.NotificatorServiceDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificatorServiceDelegateClient : System.ServiceModel.ClientBase<Zamov.srSms.NotificatorServiceDelegate>, Zamov.srSms.NotificatorServiceDelegate {
        
        public NotificatorServiceDelegateClient() {
        }
        
        public NotificatorServiceDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificatorServiceDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificatorServiceDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificatorServiceDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zamov.srSms.sendMessagesResponse Zamov.srSms.NotificatorServiceDelegate.sendMessages(Zamov.srSms.sendMessagesRequest request) {
            return base.Channel.sendMessages(request);
        }
        
        public Zamov.srSms.responseMessage sendMessages(Zamov.srSms.notification arg0) {
            Zamov.srSms.sendMessagesRequest inValue = new Zamov.srSms.sendMessagesRequest();
            inValue.arg0 = arg0;
            Zamov.srSms.sendMessagesResponse retVal = ((Zamov.srSms.NotificatorServiceDelegate)(this)).sendMessages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zamov.srSms.requestNotificationStatusResponse Zamov.srSms.NotificatorServiceDelegate.requestNotificationStatus(Zamov.srSms.requestNotificationStatusRequest request) {
            return base.Channel.requestNotificationStatus(request);
        }
        
        public Zamov.srSms.responseMessage requestNotificationStatus(Zamov.srSms.notificationRequest arg0) {
            Zamov.srSms.requestNotificationStatusRequest inValue = new Zamov.srSms.requestNotificationStatusRequest();
            inValue.arg0 = arg0;
            Zamov.srSms.requestNotificationStatusResponse retVal = ((Zamov.srSms.NotificatorServiceDelegate)(this)).requestNotificationStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zamov.srSms.requestMessageStatusResponse Zamov.srSms.NotificatorServiceDelegate.requestMessageStatus(Zamov.srSms.requestMessageStatusRequest request) {
            return base.Channel.requestMessageStatus(request);
        }
        
        public Zamov.srSms.status requestMessageStatus(Zamov.srSms.messageRequest arg0) {
            Zamov.srSms.requestMessageStatusRequest inValue = new Zamov.srSms.requestMessageStatusRequest();
            inValue.arg0 = arg0;
            Zamov.srSms.requestMessageStatusResponse retVal = ((Zamov.srSms.NotificatorServiceDelegate)(this)).requestMessageStatus(inValue);
            return retVal.@return;
        }
    }
}
